POST https://${env.dt_tenant}/api/v1/entity/infrastructure/custom/keptn
Content-Type: application/json
Authorization: Api-Token ${env.dt_api_token}

{
  "displayName": "Keptn",
  "group": "Keptn",
  "favicon": "https://pbs.twimg.com/profile_images/1089957894391398400/UgFeyejl_400x400.jpg",
  "configUrl": "https://bridge.keptn.${env.keptn_domain}",
  "type": "Event",
  "properties": {},
  "tags": [ ],
  "series": [
  {
    "timeseriesId": "custom:${type}",
    "dimensions": {
      "project": "${data.project}",
      "stage": "${data.stage}",
      "service": "${data.service}"
    },
    "dataPoints": [
      [
        ${timeutcms},
        1
      ]
    ]
  }
  ]
}