##
POST https://webhook.site/8be098d9-72af-435e-8ede-73675e4bdff2
Accept: application/json
Cache-Control: no-cache
Content-Type: application/cloudevents+json

{
  "contenttype": "application/json",
  "deploymentstrategy": "blue_green_service",
  "project": "$PROJECT",
  "service": "$SERVICE",
  "stage": "$STAGE",
  "mylabel" : "$LABEL_gitcommit",
  "mytoken" : "$ENV_TESTTOKEN",
  "shkeptncontext": "$CONTEXT",
  "event": "$EVENT",
  "source": "$SOURCE"
}
###