apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: keptnsandbox/generic-executor-service
      docker:
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  kubectl:
    defaultNamespace: keptn
    manifests:
      - deploy/service.yaml
