##
POST http://localhost:8080/
Content-Type: application/cloudevents+json

{
  "data": {
    "deployment": {
      "deploymentNames": [
        "user_managed"
      ],
      "deploymentURIsLocal": [
        ""
      ],
      "deploymentURIsPublic": [
        "http://simplenode.demo-rollout-staging.keptn08-agrabner.demo.keptn.sh/"
      ],
      "deploymentstrategy": "user_managed",
      "gitCommit": "2aed3f456ef19c901478e5e2f3ce1a489c524a37"
    },
    "message": "Successfully deployed",
    "project": "demo-rollout",
    "result": "pass",
    "service": "simplenode",
    "stage": "staging",
    "status": "succeeded"
  },
  "id": "74720cec-9366-4537-a258-be2529812c58",
  "source": "helm-service",
  "specversion": "1.0",
  "time": "2021-04-06T10:32:00.067Z",
  "type": "sh.keptn.event.deployment.finished",
  "shkeptncontext": "e4158c2f-c0c3-41cf-b641-1c01b4cbbe9f",
  "triggeredid": "ebc52b76-40c0-4ec2-b03c-36e90ea66a0b"
}
###