##
POST http://localhost:8080/
Content-Type: application/cloudevents+json

{
  "data": {
    "action" : {
      "Name" : "ActionName",
      "Action" : "myaction",
      "Description" : "Executes a generic action",
      "Value" : {
        "message" : "some message",
        "somethingelse" : "value2"
      }
    },
    "labels": {
      "Problem URL": "https://live.dynatrace.com/#problems/problemdetails;pid=-3728904940314550461_1617358188713V2"
    },
    "message": "triggered all actions",
    "project": "demo-remediation",
    "result": "pass",
    "service": "allproblems",
    "stage": "production",
    "status": "succeeded"
  },
  "id": "f0404a65-0a82-4664-a7dc-0136016377c1",
  "source": "remediation-service",
  "specversion": "1.0",
  "time": "2021-04-02T10:10:52.511Z",
  "type": "sh.keptn.event.action.triggered",
  "shkeptncontext": "2d333732-3839-4034-b934-303331343535",
  "triggeredid": "1a21f70d-336c-4bcd-a42a-0845239c3503"  
}
###