##
POST http://localhost:8080/
Content-Type: application/cloudevents+json

{
  "contenttype": "application/json",
  "data": {
    "project": "simpleproject",
    "service": "simplenode",
    "stage": "staging",
    "labels": {
        "gitcommit" : "commit-ABCDEF123123",
        "jenkinsjob" : "job1234",
        "user" : "andi"
    },
    "result": "pass",
    "status": "succeeded",
    "test": {
      "end": "2021-04-06T10:36:14Z",
      "gitCommit": "",
      "start": "2021-04-06T10:35:19Z"
    }    
  },
  "id": "3a455fb7-7e48-4be0-9e20-468a007ec1b4",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2021-04-06T10:35:19.830Z",
  "type": "sh.keptn.event.test.finished",
  "shkeptncontext": "e4158c2f-c0c3-41cf-b641-1c01b4cbbe9f",
  "shkeptnspecversion": "0.2.1"  
}
###